syntax = "proto3";

package astra;

import "vector.proto";

message Controller {
    bool a = 1;
    bool b = 2;
    bool x = 3;
    bool y = 4;

    bool left_bumper = 5;
    bool right_bumper = 6;

    bool left_stick_press = 7;
    bool right_stick_press = 8;

    bool up = 9;
    bool down = 10;
    bool right = 11;
    bool left = 12;

    bool share = 13;
    bool option = 14;
    bool logo = 15;

    float left_trigger = 16;
    float right_trigger = 17;

    Vector left_stick = 18;
    Vector right_stick = 19;

    string submodule = 20;
}
